### ISSUE TITLE
jump has stopped tracking my directories

### ISSUE THREAD

**Issue by isovector** [gsamokovarov/jump#57]
For some reason, jump no longer learns about the directories I visit.

Running zsh-5.8-1, and jump r277.56fe5f8-1. `eval "$(jump shell)"` is present in .zshrc.

**Comment by isovector** [comment]
Appears to be fixed by wiping out my `~/.jump` directory. I'm wondering if this was caused by very old (2+ years) entries.

**Comment by gsamokovarov** [comment]
You seem to be using a recent enough jump version, where I don't think `./jump` file corruptions should happen. You don't seem to have the old dir somewhere, so I can try to lookup the files, do you?

**Comment by isovector** [comment]
Sorry! I didn't think about the diagnostics until it was too late. I did inspect the scores file, and it had recent entries. Maybe the scoring for my old directories was just obliterating the new ones?

Anyway, thanks for `jump`! It's drastically improved my life --- so much so that I didn't realize until it stopped working :)

**Comment by gsamokovarov** [comment]
I'm not sure. We used to have failures where the content of the scores file would be corrupted by partial file save, so that's why I'm curious what was happening because we introduced safer file writes operations and haven't seen any issue reports since. If it happens again, please do save it so I can inspect it. 😅

Thanks for the kind words, though, I myself enjoy using `jump` a lot!
