### ISSUE TITLE
Add option to use pushd instead of cd in dir motion

### ISSUE THREAD

**Issue by underrun** [gsamokovarov/jump#64]
I would like to be able to use `j` to jump around my commonly used directories but then use `popd` to navigate back through my dir stack.

**Comment by gsamokovarov** [comment]
When I started jump, I had a goal to not require any other configuration other than the initial integration. Same for the interfaces, I want just `j`, not `jc`, `jo`, `jco` or whatever other interfaces auto jump invented. That said, I have bend this goal a bit and introduced a few config options you can set with `jump config`, BUT I think you can achieve what you want with a custom integration script. Run `jump shell` and jump will output the integration script for your shell. You can paste that output in your shell config and change the `cd` to `pushd`.

For example, I'm running on fish, and this is how I can change the integration script to use `pushd` instead of `cd`. Look for the line where the `j` functions calls `cd` and change it to `pushd`. Don't change `jump cd` to `jump pushd`, `jump cd` is the internal command we use to guess the directory we need to land on. See the `👈` mark for what line to change for fish shell in my case.

```fish
-> jump shell
# Put the line below in ~/.config/fish/config.fish:
#
#   status --is-interactive; and source (jump shell fish | psub)
#
# The following lines are autogenerated:

function __jump_add --on-variable PWD
  status --is-command-substitution; and return
  jump chdir
end

function __jump_hint
  set -l term (string replace -r '^j ' '' -- (commandline -cp))
  jump hint "$term"
end

function j
  set -l dir (jump cd "$argv")
  test -d "$dir"; and cd "$dir" #  👈  test -d "$dir"; and pushd "$dir"
end

complete --command j --exclusive --arguments '(__jump_hint)'
```
