### ISSUE TITLE
when having identically named directories across projects j isn't intuitive

### ISSUE THREAD

**Issue by McKean** [gsamokovarov/jump#8]
I would suggest prioritizing child directories or provide something like `jc` (as with autojump) to jump only within the children of the current directory.

Also, thanks for this, I'm liking it.

**Comment by gsamokovarov** [comment]
I support `j fuzzy_match_parent_dir/fuzzy_match_child_dir` for this. If you have `/Development/chaos/website` and `/Development/raketa/website` you can go around with: `j ch/web` or `j ra/web`. I call this deep search. This actually regressed around `0.9.0`, but have been fixed in the latest release, `0.11.0`, which I just pushed out.

Alternatively, you can use pins to, basically, do manual shortcuts if the matching fails. I did this because I had the following projects:

```
/Users/genadi/Development/brownie
├── ./brownie-dev-box
└── ./brownie-points-webapp
```

`j bweb` always ended up in `brownie-dev-box`, because it had better score. With pins, you can go to `brownie-points-webapp` and `jump pin bweb` to force manually override jump's search for `j bweb`. This is new `0.11.0`.

You can read more about the deep search and the pins at the [`0.11.0` release notes](https://github.com/gsamokovarov/jump/releases/tag/v0.11.0). May need to wait a bit for it to hit homebrew.

Does any of the answers above helped you?

**Comment by gsamokovarov** [comment]
I'll close it, please feel free to reopen and discuss more if you feel the solutions above aren't intuitive enough. ✌️

**Comment by McKean** [comment]
sorry for my late reply, the / really does solve this issue. thanks!

**Comment by gsamokovarov** [comment]
Glad to hear that. 🙂
